### ISSUE TITLE
Native Support of Mattermost plugins

### ISSUE THREAD

**Issue by rjferguson21** [defenseunicorns/uds-package-mattermost#7]
### Is your feature request related to a problem? Please describe.
Users of Mattermost will want to use plugins. Currently, whomever is managing Mattermost deployments would need to configure plugins manually, post-deployment. 

### Describe the solution you'd like
A way to manage Mattermost plugins via code at the package level vs bundle or manually. 

### Describe alternatives you've considered
Doing it manually

### Additional context
🐸

https://github.com/mattermost/mattermost-plugin-ai

**Comment by mjnagel** [comment]
This should be easy from a manual perspective. It does require one bundle override to enable plugin uploads:
```yaml
    overrides:
        mattermost-enterprise-edition:
          values:
            - path: "mattermostApp.extraEnv"
              value:
                - name: MM_PLUGINSETTINGS_ENABLEUPLOADS
                  value: "true"
```

After that the plugin can be installed and enabled the same way the docs list - https://github.com/mattermost/mattermost-plugin-ai?tab=readme-ov-file#install

For an automatic approach we should be able to use https://github.com/mattermost/mattermost-helm/blob/master/charts/mattermost-enterprise-edition/values.yaml#L206-L233 which shouldn't be too difficult until we assume airgap 🤪

**Comment by mjnagel** [comment]
Discovered in further testing that doing the above mentioned override will cause envs to get wiped out for other config (filestorage/sso). Resolving that in the linked PR, assuming that is merged the new way to approach will be:
```yaml
    overrides:
      mattermost:
        uds-mattermost-config:
          values:
            - path: "config.enablePluginUploads"
              value: "true"
```
